version: 0.2
env:
  variables:
    CHANGELIST: "-SNAPSHOT"
    AWS_ACCOUNT_ID: "518241560725"

phases:

  install:
    runtime-versions:
      java: corretto21
    commands:
      - yum -y install glibc-all-langpacks
      - export LC_ALL="en_US.UTF-8"
      - export LANG="en_US.UTF-8"
      - java -version
      - yum -y upgrade
      - java -version
      - aws s3 sync s3://dev.tools.s3.devops.docbyte.cloud/ ~/tools/
      - chmod a+x -R ~/tools/
      - . ~/tools/prepEnv.sh
      - . ~/tools/codebuild-gittools.sh
      - echo Build Started
      - . ci/codebuild/installRequirements.sh
      - . ci/codebuild/setupTestEnv.sh
  pre_build:
    commands:
      - . ~/tools/codebuild-versioning.sh
      - REGISTRY_URI=518241560725.dkr.ecr.eu-west-1.amazonaws.com
      - REPOSITORY_URI=518241560725.dkr.ecr.eu-west-1.amazonaws.com/docbyte-nuxeo
      - IMAGE_TAG=${VERSION:=latest}
      - export MAVEN_ARGS=" -Prelease,distrib,docker -nsu -ntp -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Dnuxeo.skip.enforcer=true -Dcustom.environment=mongodb -Dcustom.environment.log.dir=target-mongodb -Dnuxeo.test.core=mongodb -Ddocker.verbose=true"
      - ./update-version.sh

  build:
    commands:
      - LANG=en_US.utf8 mvn -pl "!cloud.docbyte.nuxeo.docker:nuxeo-benchmark-docker-image" $MVN_GOAL $MAVEN_ARGS -fae
      - mvn -DskipTests=true $MAVEN_ARGS -f parent/pom.xml $MVN_GOAL
      - docker tag nuxeo/nuxeo:2025.x $REPOSITORY_URI:latest
      - docker tag nuxeo/nuxeo:2025.x $REPOSITORY_URI:$IMAGE_TAG
      - echo Build finished on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Deployment done `date`
    finally:
      - docker images
reports:
  SurefireReports:
    files:
      - 'target-mongodb/surefire-reports/**/*'
      - '**/target-mongodb/surefire-reports/**/*'
