# for nuxeo unit tests
nuxeo.test.stream=kafka
nuxeo.test.kafka.servers=${TEST_KAFKA_K8S_OBJECT}.${NAMESPACE}.${TEST_SERVICE_DOMAIN_SUFFIX}:${TEST_KAFKA_PORT}

# for nuxeo-stream (the module could be taken into account on Run unit tests stage)
kafka=true
kafka.bootstrap.servers=${TEST_KAFKA_K8S_OBJECT}.${NAMESPACE}.${TEST_SERVICE_DOMAIN_SUFFIX}:${TEST_KAFKA_PORT}
